package render

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/open-platform-model/docs-kit/internal/command"
	"github.com/open-platform-model/docs-kit/internal/extract/cobra"
)

// The cli's command reference, as its cmdref generator committed it, marks
// its generated block with these comments; the cobra renderer writes the
// same pages without them.
const (
	cmdrefBegin = "<!-- generated by task docs:reference from the opm cobra commands; DO NOT EDIT -->\n\n"
	cmdrefEnd   = "\n<!-- end generated -->\n"
)

// TestCLICommandParity renders a cli checkout's command tree, printed by
// its hack/docskit-dump program, with the cli's planned config, and
// compares every page with the one cmdref committed under
// docs/site/reference/cli/. It runs only when OPM_CLI_CHECKOUT names such a
// checkout.
func TestCLICommandParity(t *testing.T) {
	cli := os.Getenv("OPM_CLI_CHECKOUT")
	if cli == "" {
		t.Skip("OPM_CLI_CHECKOUT is not set")
	}
	if _, err := os.Stat(filepath.Join(cli, "hack", "docskit-dump")); err != nil {
		t.Skipf("%s has no hack/docskit-dump", cli)
	}
	run := &command.Runner{Dir: cli, Project: "cli", Version: "edge", Twice: true}
	dump, err := run.Run(context.Background(), []string{"go", "run", "./hack/docskit-dump"}, cobra.DumpSchema)
	if err != nil {
		t.Fatal(err)
	}
	m, err := cobra.FromDump(dump, cobra.Options{
		Section: "reference/cli/", Title: "CLI Reference",
		Description: "Every opm command and flag, generated from the CLI's cobra commands.",
		Weight:      2, Citations: "strip",
	})
	if err != nil {
		t.Fatal(err)
	}
	data, err := m.Encode()
	if err != nil {
		t.Fatal(err)
	}
	pages, err := cobraRenderer{}.Render(data, Target{Kind: KindDocs, Root: "/docs/"})
	if err != nil {
		t.Fatal(err)
	}
	ref := filepath.Join(cli, "docs", "site", "reference", "cli")
	var want []string
	entries, err := os.ReadDir(ref)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		b, err := os.ReadFile(filepath.Join(ref, e.Name()))
		if err == nil && bytes.Contains(b, []byte(cmdrefBegin)) {
			want = append(want, "reference/cli/"+e.Name())
		}
	}
	var got []string
	for _, p := range pages {
		got = append(got, p.Path)
		committed, err := os.ReadFile(filepath.Join(cli, "docs", "site", filepath.FromSlash(p.Path)))
		if err != nil {
			t.Errorf("%s: cmdref wrote no such page", p.Path)
			continue
		}
		stripped := strings.Replace(strings.Replace(string(committed), cmdrefBegin, "", 1), cmdrefEnd, "", 1)
		if stripped != p.Body {
			t.Errorf("%s differs from cmdref's page:\n%s", p.Path, firstDiff(stripped, p.Body))
		}
	}
	sort.Strings(got)
	sort.Strings(want)
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Errorf("pages %v, cmdref's %v", got, want)
	}
}

// firstDiff shows the first line where two pages differ.
func firstDiff(a, b string) string {
	al, bl := strings.Split(a, "\n"), strings.Split(b, "\n")
	for i := 0; i < len(al) || i < len(bl); i++ {
		var x, y string
		if i < len(al) {
			x = al[i]
		}
		if i < len(bl) {
			y = bl[i]
		}
		if x != y {
			return fmt.Sprintf("line %d:\n  cmdref: %s\n  cobra:  %s", i+1, x, y)
		}
	}
	return ""
}
