package render

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/open-platform-model/docs-kit/internal/doctext"
	"github.com/open-platform-model/docs-kit/internal/extract/crd"
)

// operatorOptions is the crd source opm-operator's docs-kit.cue declares.
func operatorOptions(root string) crd.Options {
	weight := 7
	return crd.Options{
		Root: root, Dir: "./config/crd/bases", Samples: "./config/samples",
		HideSamplesMatching: []string{"testing.opmodel.dev"},
		StripLabels:         map[string]string{"app.kubernetes.io/name": "opm-operator", "app.kubernetes.io/managed-by": "kustomize"},
		Page: crd.Page{
			Path: "reference/operator-resources.md", Title: "Operator resources", Weight: &weight,
			Description: "One generated entry per operator resource kind: ModuleInstance, ModulePackage, Platform and TransformerRegistration.",
		},
		Order: []string{"ModuleInstance", "ModulePackage", "Platform", "TransformerRegistration"},
		ReconciledBy: map[string]string{
			"ModuleInstance": "moduleinstance", "ModulePackage": "modulepackage",
			"Platform": "platform", "TransformerRegistration": "transformerregistration",
		},
		Doc: doctext.Link,
	}
}

// crdrefServedBy matches crdref's "Served by" sentence, which named the
// product: "The operator's `x` controller watches every X."
var crdrefServedBy = regexp.MustCompile("(?m)^The operator's (`[^`]+`) controller watches every ([A-Z][A-Za-z0-9]*)\\.$")

// servedByWording rewrites crdref's "Served by" sentences into the
// renderer's product-neutral wording, the one place the entries depart from
// crdref's block on purpose.
func servedByWording(block string) string {
	return crdrefServedBy.ReplaceAllString(block, "The $1 reconciler watches every $2.")
}

// TestOperatorCRDParity compares the crd page's entries with the block
// opm-operator's hack/crdref generated between its markers in
// docs/site/reference/operator-resources.md: the copy under
// testdata/operator (see its SOURCE), or the operator checkout
// OPM_OPERATOR_CHECKOUT names.
func TestOperatorCRDParity(t *testing.T) {
	root := os.Getenv("OPM_OPERATOR_CHECKOUT")
	if root == "" {
		root = filepath.Join("testdata", "operator")
	}
	page, err := os.ReadFile(filepath.Join(root, "docs", "site", "reference", "operator-resources.md"))
	if err != nil {
		t.Fatal(err)
	}
	const begin, end = "<!-- BEGIN GENERATED by hack/crdref", "<!-- END GENERATED by hack/crdref -->"
	s := string(page)
	i, j := strings.Index(s, begin), strings.Index(s, end)
	if i < 0 || j < i {
		t.Fatalf("%s holds no crdref block", root)
	}
	i += strings.Index(s[i:], "\n") + 1
	want := servedByWording(strings.Trim(s[i:j], "\n") + "\n")

	m, err := crd.Extract(operatorOptions(root))
	if err != nil {
		t.Fatal(err)
	}
	data, err := m.Encode()
	if err != nil {
		t.Fatal(err)
	}
	pages, err := crdRenderer{}.Render(data, Target{Kind: KindDocs, Root: "/docs/"})
	if err != nil {
		t.Fatal(err)
	}
	got := pages[0].Tail
	if got == want {
		return
	}
	gl, wl := strings.Split(got, "\n"), strings.Split(want, "\n")
	for n := 0; n < len(gl) || n < len(wl); n++ {
		var g, w string
		if n < len(gl) {
			g = gl[n]
		}
		if n < len(wl) {
			w = wl[n]
		}
		if g != w {
			t.Fatalf("line %d differs from crdref's block:\n got: %q\nwant: %q", n+1, g, w)
		}
	}
}
