package render_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/open-platform-model/docs-kit/internal/config"
	"github.com/open-platform-model/docs-kit/internal/extract/cuedefs"
	"github.com/open-platform-model/docs-kit/internal/render"
)

// TestCoreDefinitionsParity builds core's definitions with core's planned
// docs-kit.cue and compares every page with the page core's refgen
// committed at the checkout's commit, its marker comments removed.
// Opt-in: it runs only when OPM_CORE_CHECKOUT names a core checkout.
func TestCoreDefinitionsParity(t *testing.T) {
	root := os.Getenv("OPM_CORE_CHECKOUT")
	if root == "" {
		t.Skip("OPM_CORE_CHECKOUT is unset")
	}
	c, err := config.Load("../extract/cuedefs/testdata/core-docs-kit.cue")
	if err != nil {
		t.Fatal(err)
	}
	var cfg cuedefs.Config
	if err := c.Bundles["core"].Sources[0].Value.Decode(&cfg); err != nil {
		t.Fatal(err)
	}
	m, err := cuedefs.Extract(cuedefs.Options{Root: root, Config: cfg, Version: "edge"})
	if err != nil {
		t.Fatal(err)
	}
	// The renderer reads the data file as written.
	data, err := m.Encode()
	if err != nil {
		t.Fatal(err)
	}
	r, err := render.For(cuedefs.SchemaID)
	if err != nil {
		t.Fatal(err)
	}
	pages, err := r.Render(data, render.Target{Kind: render.KindDocs, Root: "/docs/", Segment: "2.0", Edge: true, Version: "edge"})
	if err != nil {
		t.Fatal(err)
	}
	committed := filepath.Join(root, "docs", "site", "reference", "definitions")
	entries, err := os.ReadDir(committed)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != len(pages) {
		t.Errorf("refgen committed %d pages, opm-docs renders %d", len(entries), len(pages))
	}
	for _, p := range pages {
		b, err := os.ReadFile(filepath.Join(committed, strings.TrimPrefix(p.Path, cfg.Section)))
		if err != nil {
			t.Errorf("%s: %v", p.Path, err)
			continue
		}
		if want := withoutMarkers(string(b)); p.Body != want {
			t.Errorf("%s differs from refgen's page:\n%s", p.Path, lineDiff(want, p.Body))
		}
	}
	t.Logf("%d pages compared with refgen's", len(pages))
}

const (
	beginMarker = "<!-- generated by task docs:reference from the CUE definitions in src/; DO NOT EDIT -->\n\n"
	endMarker   = "\n<!-- end generated -->\n"
)

func withoutMarkers(s string) string {
	return strings.Replace(strings.Replace(s, beginMarker, "", 1), endMarker, "", 1)
}

// lineDiff names the first line where two pages differ.
func lineDiff(want, got string) string {
	w, g := strings.Split(want, "\n"), strings.Split(got, "\n")
	for i := 0; i < len(w) || i < len(g); i++ {
		var a, b string
		if i < len(w) {
			a = w[i]
		}
		if i < len(g) {
			b = g[i]
		}
		if a != b {
			return fmt.Sprintf("line %d:\n  refgen:   %s\n  opm-docs: %s", i+1, a, b)
		}
	}
	return "identical lines"
}
